# Generated by Django 5.0.1 on 2024-02-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
